In [1]:
import pandas as pd

from torch.utils.data import DataLoader

In [2]:
class CSVLoader(object):
    '''
        loads csv file and gives you timeframe back
    '''
    def __init__(self, data_path, timeframe=5):
        self.data = pd.read_csv(data_path)
        self.timeframe = timeframe
    
    def __len__(self):
        '''
            Number of values in the dataframe
        '''
        return (self.data.shape[0] - self.timeframe)
        
    def __getitem__(self, index):
        '''
            Get X rows out of the csv file reshaped to a numpy array in one row
        '''
        result = self.data[index: index + self.timeframe]
        result = result.values.reshape(1, self.timeframe * self.data.shape[1])
        return result


In [3]:
def get_loader(data_path='data/autoencoder_v1_PAH3DEEUR_1 Min_Bid_2008.10.21_2018.10.27', 
               batch_size = 64):
    '''
        loads the dataloader object from the dataset
    '''
    loader = CSVLoader(data_path=data_path, timeframe = 5)
    data_loader = DataLoader(dataset=loader, batch_size = batch_size)
    return data_loader

In [4]:
dl = get_loader()

In [7]:
data = pd.read_csv('data/autoencoder_v1_PAH3DEEUR_1 Min_Bid_2008.10.21_2018.10.27')

In [10]:
data[0].as_type(float)

KeyError: 0

In [5]:
ds = iter(dl)
for i in range(10):
    print(ds.next()[0])

tensor([[ 0.5780,  0.5400,  0.0540, -0.0380, -0.5240,  0.4860,  0.0162,  0.3440,
          0.0930,  0.2760, -0.2510, -0.0680, -0.1830,  0.0665,  0.0840,  0.0750,
          0.0740, -0.0090, -0.0100,  0.0010,  0.0028,  0.1390,  0.1040,  0.0390,
         -0.0350, -0.1000,  0.0650,  0.0101,  0.1440,  0.1330,  0.0000, -0.0110,
         -0.1440,  0.1330,  0.0075]], dtype=torch.float64)
tensor([[ 0.0510,  0.0210,  0.0320, -0.0300, -0.0190, -0.0110,  0.0029,  0.0200,
          0.0120,  0.0200, -0.0080,  0.0000, -0.0080,  0.0006,  0.0250,  0.0100,
          0.0080, -0.0150, -0.0170,  0.0020,  0.0026,  0.0290,  0.0290,  0.0180,
          0.0000, -0.0110,  0.0110,  0.0024,  0.0170,  0.0170,  0.0060,  0.0000,
         -0.0110,  0.0110,  0.0020]], dtype=torch.float64)
tensor([[ 0.1450,  0.0060,  0.1190, -0.1390, -0.0260, -0.1130,  0.0120,  0.0340,
          0.0100,  0.0280, -0.0240, -0.0060, -0.0180,  0.0089,  0.0880,  0.0650,
          0.0330, -0.0230, -0.0550,  0.0320,  0.0277,  0.0960,  0.0810, 